CREATE TABLE "usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(150) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "data_cadastro" timestamp
);

CREATE TABLE "perfil_usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int UNIQUE NOT NULL,
  "ambiente" varchar(30) NOT NULL,
  "tempo" varchar(30) NOT NULL,
  "recursos" varchar(30) NOT NULL,
  "interlocutores" varchar(30) NOT NULL,
  "origem_atualizacao" varchar(30) NOT NULL DEFAULT 'onboarding',
  "atualizado_em" timestamp
);

CREATE TABLE "historico_perfil" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int NOT NULL,
  "ambiente" varchar(30) NOT NULL,
  "tempo" varchar(30) NOT NULL,
  "recursos" varchar(30) NOT NULL,
  "interlocutores" varchar(30) NOT NULL,
  "origem" varchar(30) NOT NULL,
  "motivo" text,
  "data_registro" timestamp
);

CREATE TABLE "questionario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(150) NOT NULL,
  "descricao" text,
  "ativo" boolean NOT NULL DEFAULT true,
  "data_criacao" timestamp
);

CREATE TABLE "pergunta" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "questionario_id" int NOT NULL,
  "titulo" varchar(255) NOT NULL,
  "descricao" text,
  "tipo" varchar(30) NOT NULL DEFAULT 'unica',
  "ordem" int NOT NULL,
  "obrigatoria" boolean NOT NULL DEFAULT true,
  "campo_perfil" varchar(30)
);

CREATE TABLE "opcao_pergunta" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pergunta_id" int NOT NULL,
  "codigo" varchar(50) NOT NULL,
  "texto" varchar(255) NOT NULL,
  "valor" varchar(100),
  "ordem" int NOT NULL,
  "ativa" boolean NOT NULL DEFAULT true
);

CREATE TABLE "avaliacao_usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int NOT NULL,
  "questionario_id" int NOT NULL,
  "tipo" varchar(30) NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'em_andamento',
  "data_inicio" timestamp,
  "data_conclusao" timestamp
);

CREATE TABLE "resposta_usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "avaliacao_id" int NOT NULL,
  "pergunta_id" int NOT NULL,
  "opcao_id" int,
  "resposta_texto" text,
  "resposta_numero" decimal,
  "data_resposta" timestamp
);

CREATE TABLE "competencia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) UNIQUE NOT NULL,
  "descricao" text,
  "data_criado" timestamp
);

CREATE TABLE "atividade" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(200) NOT NULL,
  "competencia_id" int NOT NULL,
  "dificuldade" int NOT NULL,
  "duracao_min" int NOT NULL,
  "ambiente" varchar(30) NOT NULL,
  "tempo" varchar(30) NOT NULL,
  "recursos" varchar(30) NOT NULL,
  "interlocutores" varchar(30) NOT NULL,
  "evidencia_exigida" varchar(50) NOT NULL,
  "descricao" text,
  "data_criado" timestamp
);

CREATE TABLE "recomendacao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int NOT NULL,
  "atividade_id" int NOT NULL,
  "data_gerada" date NOT NULL,
  "regra_usada" varchar(100) NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'gerada',
  "motivo_recusa" text,
  "data_decisao" timestamp
);

CREATE TABLE "execucao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recomendacao_id" int UNIQUE NOT NULL,
  "evidencia_arquivo" varchar(255),
  "data_envio" timestamp,
  "feedback" text,
  "progresso_atualizado" decimal(5,2)
);

ALTER TABLE "perfil_usuario" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "historico_perfil" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pergunta" ADD FOREIGN KEY ("questionario_id") REFERENCES "questionario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "opcao_pergunta" ADD FOREIGN KEY ("pergunta_id") REFERENCES "pergunta" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "avaliacao_usuario" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "avaliacao_usuario" ADD FOREIGN KEY ("questionario_id") REFERENCES "questionario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resposta_usuario" ADD FOREIGN KEY ("avaliacao_id") REFERENCES "avaliacao_usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resposta_usuario" ADD FOREIGN KEY ("pergunta_id") REFERENCES "pergunta" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resposta_usuario" ADD FOREIGN KEY ("opcao_id") REFERENCES "opcao_pergunta" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "atividade" ADD FOREIGN KEY ("competencia_id") REFERENCES "competencia" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recomendacao" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recomendacao" ADD FOREIGN KEY ("atividade_id") REFERENCES "atividade" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "execucao" ADD FOREIGN KEY ("recomendacao_id") REFERENCES "recomendacao" ("id") DEFERRABLE INITIALLY IMMEDIATE;